
DROP TABLE IF EXISTS Usuario CASCADE;
DROP TABLE IF EXISTS Post CASCADE;
DROP TABLE IF EXISTS Curtida CASCADE;
DROP TABLE IF EXISTS Amizade CASCADE;
DROP TABLE IF EXISTS Comentario CASCADE;



CREATE TABLE Usuario(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_completo VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    apelido VARCHAR(50),
    data_nascimento DATE NOT NULL,
    senha VARCHAR(128) NOT NULL,
    url_imagem VARCHAR(512)
);

CREATE TABLE Post(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    texto_post VARCHAR(150) NOT NULL,
    permissao_visualizacao VARCHAR(7) NOT NULL,
    url_imagem_POST VARCHAR(512),
    id_usuario BIGINT NOT NULL,
	data_postagem TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_post_usuario FOREIGN KEY (id_usuario) REFERENCES Usuario(id) ON DELETE CASCADE
);

CREATE TABLE Curtida(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,


    CONSTRAINT fk_curtida_usuario FOREIGN KEY (usuario_id) REFERENCES Usuario(id) ON DELETE CASCADE,
    CONSTRAINT fk_curtida_post FOREIGN KEY (post_id) REFERENCES Post(id) ON DELETE CASCADE
);

CREATE TABLE Comentario (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    texto_comentario VARCHAR(150) NOT NULL,
    usuario_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,



    CONSTRAINT fk_comentario_usuario FOREIGN KEY (usuario_id) REFERENCES Usuario(id) ON DELETE CASCADE,
    CONSTRAINT fk_comentario_post FOREIGN KEY (post_id) REFERENCES Post(id) ON DELETE CASCADE
);

CREATE TABLE Amizade(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    solicitante_id BIGINT NOT NULL,
    solicitado_id BIGINT NOT NULL,
    status VARCHAR(8) NOT NULL,



    CONSTRAINT fk_amizade_solicitante FOREIGN KEY (solicitante_id) REFERENCES Usuario(id) ON DELETE CASCADE,

    CONSTRAINT fk_amizade_solicitado FOREIGN KEY (solicitado_id) REFERENCES Usuario(id) ON DELETE CASCADE,

    CHECK (solicitante_id <> solicitado_id)

);